baseurl = "https://yihui.org/"
languageCode = "en-us"
title = "Yihui Xie | 谢益辉"
theme = "hugo-ivy"
disqusShortname = "yihui"
ignoreFiles = [
  "\\.Rmd$",
  "_files$",
  "_cache$"
]
hasCJKLanguage = true
enableEmoji = true
footnotereturnlinkcontents = "↩"
rssLimit = 100.0

[permalinks]
cn = "/cn/:year/:month/:slug/"
en = "/en/:year/:month/:slug/"

[menu]

  [[menu.main]]
  name = "About"
  url = "/en/about/"
  weight = 1.0

  [[menu.main]]
  name = "Blog"
  url = "/en/"
  weight = 2.0

  [[menu.main]]
  name = "关于"
  url = "/cn/about/"
  weight = 3.0

  [[menu.main]]
  name = "日志"
  url = "/cn/"
  weight = 4.0

  [[menu.en]]
  name = "Home"
  url = "/"
  weight = 1.0

  [[menu.en]]
  name = "About"
  url = "/en/about/"
  weight = 2.0

  [[menu.en]]
  name = "Blog"
  url = "/en/"
  weight = 3.0

  [[menu.en]]
  name = "Vitae"
  url = "/en/vitae/"
  weight = 4.0

  [[menu.en]]
  name = "中文"
  url = "/cn/"
  weight = 5.0

  [[menu.cn]]
  name = "首页"
  url = "/"
  weight = 1.0

  [[menu.cn]]
  name = "关于"
  url = "/cn/about/"
  weight = 2.0

  [[menu.cn]]
  name = "日志"
  url = "/cn/"
  weight = 3.0

  [[menu.cn]]
  name = "简历"
  url = "/cn/vitae/"
  weight = 4.0

  [[menu.cn]]
  name = "菜谱"
  url = "/cn/recipe/"
  weight = 5.0

  [[menu.cn]]
  name = "English"
  url = "/en/"
  weight = 6.0

  [[menu.knitr]]
  name = "Home"
  url = "/knitr/"
  weight = 1.0

  [[menu.knitr]]
  name = "Options"
  url = "/knitr/options/"
  weight = 2.0

  [[menu.knitr]]
  name = "Hooks"
  url = "/knitr/hooks/"
  weight = 3.0

  [[menu.knitr]]
  name = "Examples"
  url = "/knitr/demos/"
  weight = 4.0

  [[menu.knitr]]
  name = "FAQ"
  url = "/knitr/faq/"
  weight = 5.0

  [[menu.knitr]]
  name = "Github repo"
  pre = "github"
  url = "https://github.com/yihui/knitr"
  weight = 6.0

  [[menu.knitr]]
  name = "Yihui Xie"
  url = "/"
  weight = 7.0

  [[menu.animation]]
  name = "Home"
  url = "/animation/"
  weight = 1.0

  [[menu.animation]]
  name = "Examples"
  url = "/animation/examples/"
  weight = 2.0

  [[menu.animation]]
  name = "Export"
  url = "/animation/export/"
  weight = 3.0

  [[menu.animation]]
  name = "Resources"
  url = "/animation/resources/"
  weight = 4.0

  [[menu.animation]]
  name = "Github repo"
  pre = "github"
  url = "https://github.com/yihui/animation"
  weight = 5.0

  [[menu.animation]]
  name = "Yihui Xie"
  url = "/"
  weight = 6.0

  [[menu.tinytex]]
  name = "Home"
  url = "/tinytex/"
  weight = 1.0

  [[menu.tinytex]]
  name = "FAQs"
  url = "/tinytex/faq/"
  weight = 2.0

  [[menu.tinytex]]
  name = "R package"
  url = "/tinytex/r/"
  weight = 3.0

  [[menu.tinytex]]
  name = "Hall of Pain"
  url = "/tinytex/pain/"
  weight = 4.0

  [[menu.tinytex]]
  name = "中文文档"
  url = "/tinytex/cn/"
  weight = 5.0

  [[menu.tinytex]]
  name = "Github repo"
  pre = "github"
  url = "https://github.com/yihui/tinytex"
  weight = 6.0

  [[menu.tinytex]]
  name = "Yihui Xie"
  url = "/"
  weight = 7.0

[params]
description = "Personal website of Yihui Xie; 谢益辉的个人网站"
footer = "&copy; [Yihui Xie](/) 2005 - 2019"
disqusURL = "https://yihui.org"
customJS = [
  "js/fix-toc.js",
  "js/center-img.js",
  "js/right-quote.js",
  "js/no-highlight.js",
  "js/fix-footnote.js",
  "js/math-code.js",
  "js/external-link.js",
  "js/alt-title.js",
  "js/header-link.js"
]
githubContentURL = "https://github.com/rbind/yihui/edit/master/content/"
twitterImage = "/images/logo.png"
highlightjsVersion = "9.12.0"
highlightjsCDN = "//cdnjs.cloudflare.com/ajax/libs"
highlightjsLang = [
  "r",
  "yaml",
  "tex"
]
highlightjsTheme = "github"

  [params.logo]

    [params.logo.en]
    img = "/images/logo.png"
    url = "/"
    alt = "Yihui Xie"
    tag = ""

    [params.logo.knitr]
    img = "/knitr/images/knit-logo.png"
    url = "/knitr/"
    alt = "knitr logo"
    tag = "knitr: elegant, flexible, and fast dynamic report generation with R"

    [params.logo.tinytex]
    img = "/images/logo-tinytex.png"
    url = "/tinytex/"
    alt = "tinytex logo"
    tag = "TinyTeX: A lightweight and easy-to-maintain LaTeX distribution"

  [params.author]
  en = "Yihui Xie"
  cn = "谢益辉"
  animation = "Yihui Xie & Lijia Yu"

  [params.lang]

    [params.lang.edit]
    cn = "编辑"

    [params.lang.license]
    cn = "版权"

    [params.lang.subscribe]
    cn = "订阅"

[blackfriday]
extensionsmask = [
  "noIntraEmphasis"
]
fractions = false