[[redirects]]
    from = "http://yfei.netlify.com/*"
    to = "http://yfei.page/:splat"
    status = 301
    force = true

[[redirects]]
    from = "http://agfun.netlify.com/*"
    to = "http://yfei.page/agfun:splat"
    status = 301
    force = true

[[redirects]]
    from = "http://ex4calc.netlify.com/*"
    to = "http://yfei.page/ex4calc:splat"
    status = 301
    force = true

[[redirects]]
    from = "http://maple4calc.netlify.com/*"
    to = "http://yfei.page/maple4calc:splat"
    status = 301
    force = true