baseurl: /
languageCode: en-us
DefaultContentLanguage: en
hasCJKLanguage: 'true'
theme: hugo-xmin
googleAnalytics: ''
disqusShortname: ''
ignoreFiles:
  - \.Rmd$
  - \.Rmarkdown$
  - _files$
  - _cache$
footnotereturnlinkcontents: ↩
permalinks:
  en: 'en/:year/:month/:day/:slug/'
  cn: 'cn/:year/:month/:day/:slug/'
menu:
  main:
    - name: Home
      url: /
      weight: 1
    - name: Blog
      url: /en/
      weight: 2
    - name: 博客
      url: /cn/
      weight: 3
  en:
    - name: Home
      url: /
      weight: 1
    - name: Blog
      url: /en/
      weight: 2
    - name: 中文
      url: /cn/
      weight: 5
  cn:
    - name: 首页
      url: /
      weight: 1
    - name: 博客
      url: /cn/
      weight: 2
    - name: English
      url: /en/
      weight: 4
params:
  footer: >-
    &copy; [Fei Ye](https://yfei.page) 2019 |
    [Github](https://github.com/fyemath) 
  author:
    en: Fei Ye
    cn: 叶飞
